// The Workers example (examples/workers) inside workerd: bundled as Wrangler would bundle it, with
// D1, its committed migration, waitUntil and the Cron Trigger, run by Miniflare. Its outbound
// requests go to the mock SCIM app and webhook receiver. Everything is driven over HTTP, as a
// browser and the Cron Trigger would.
import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { getMigrations } from "better-auth/db/migration";
import { build } from "esbuild";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createAuth, type Env } from "../../examples/workers/src/auth";
import { mockScim } from "../support/mock-scim";
import { mockWebhook } from "../support/mock-webhook";

const example = (path: string) => fileURLToPath(new URL(`../../examples/workers/${path}`, import.meta.url));
const MIGRATION = example("migrations/0001_init.sql");
const ORIGIN = "https://example.test";
const app = mockScim();
const hook = mockWebhook();
const env = {
  BETTER_AUTH_URL: ORIGIN,
  BETTER_AUTH_SECRET: "example-test-secret-that-is-at-least-32-characters",
  SCIM_URL: app.url,
  SCIM_TOKEN: "test-token",
  WEBHOOK_URL: "https://hooks.example.com/scim",
  WEBHOOK_SECRET: "webhook-secret-that-is-at-least-32-characters-long",
  ADMIN_EMAILS: "admin@example.test",
  DEV_MAILBOX: "true",
};

/** The SQL Better Auth's migrator writes for the example's options, from an empty SQLite database. */
async function migrationSql() {
  const options = createAuth({ ...env, DB: undefined as never } as Env, { database: new DatabaseSync(":memory:") }).options;
  return `-- Better Auth, its admin and organization plugins, and better-auth-scim-provisioning.\n-- Generated by Better Auth's migrator; test/example/workers.test.ts checks it's current.\n${(await (await getMigrations(options)).compileMigrations()).trim()}\n`;
}

let mf: Miniflare;
const call = (path: string, init: RequestInit = {}) => mf.dispatchFetch(`${ORIGIN}${path}`, { redirect: "manual", ...init, headers: { origin: ORIGIN, ...init.headers } } as never) as unknown as Promise<Response>;
const cookieOf = (res: Response) => res.headers.getSetCookie().map((c) => c.split(";", 1)[0]).join("; ");
const until = async (what: () => boolean) => {
  for (let i = 0; i < 100 && !what(); i++) await new Promise((r) => setTimeout(r, 50));
  return what();
};

/** Sign up, open the verification link from the dev mailbox, and return the session cookie. */
async function verifiedUser(email: string, name: string) {
  const up = await call("/api/auth/sign-up/email", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password: "correct-horse-battery", name }) });
  expect(up.status, await up.clone().text()).toBe(200);
  const { link } = (await (await call(`/dev/mailbox?email=${encodeURIComponent(email)}`)).json()) as { link: string };
  const verified = await call(new URL(link).pathname + new URL(link).search);
  expect([200, 302]).toContain(verified.status);
  return cookieOf(verified);
}

beforeAll(async () => {
  const committed = readFileSync(MIGRATION, "utf8");
  const current = await migrationSql();
  if (process.env.UPDATE_EXAMPLE_MIGRATION) writeFileSync(MIGRATION, current);
  else expect(committed, "examples/workers/migrations/0001_init.sql is out of date: rerun with UPDATE_EXAMPLE_MIGRATION=1").toBe(current);

  // Bundled for workerd as Wrangler does it; the package itself from this repository's source.
  const bundle = await build({
    entryPoints: [example("src/index.ts")],
    bundle: true,
    write: false,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    conditions: ["workerd", "worker", "browser"],
    mainFields: ["module", "main"],
    external: ["cloudflare:*", "node:*"],
    alias: { "better-auth-scim-provisioning": fileURLToPath(new URL("../../src/index.ts", import.meta.url)) },
    logLevel: "silent",
  });
  mf = new Miniflare(
    convertV4MiniflareOptions({
      modules: true,
      script: bundle.outputFiles[0]!.text,
      compatibilityDate: "2026-10-01",
      compatibilityFlags: ["nodejs_compat"],
      d1Databases: ["DB"],
      bindings: env,
      // The Worker's outbound requests: the SCIM app and the webhook receiver, nothing else.
      outboundService: async (request: Request) => {
        const init = { method: request.method, headers: Object.fromEntries(request.headers), ...(request.method === "GET" || request.method === "HEAD" ? {} : { body: await request.text() }) };
        if (request.url.startsWith(app.url)) return app.fetch(request.url, init);
        if (request.url === env.WEBHOOK_URL) return hook.fetch(request.url, init);
        return new Response("no such host in this test", { status: 502 });
      },
    } as never),
  );
  const db = await mf.getD1Database("DB");
  for (const statement of committed.split(/;\s*$/m).map((s) => s.replace(/^--.*$/gm, "").trim()).filter(Boolean)) await db.prepare(statement).run();
}, 60_000);

afterAll(async () => {
  await mf?.dispose();
});

describe("the Workers example", () => {
  let admin = "";
  let ada = "";

  it("a verified user is provisioned right after the response (waitUntil), to the SCIM app and the webhook", async () => {
    const up = await call("/api/auth/sign-up/email", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: "early@example.test", password: "correct-horse-battery", name: "Not Verified" }) });
    expect(up.status).toBe(200);
    ada = await verifiedUser("ada@example.test", "Ada Lovelace");
    expect(await until(() => [...app.users.values()].some((u) => u.userName === "ada@example.test"))).toBe(true);
    expect([...app.users.values()].map((u) => u.userName)).not.toContain("early@example.test");
    expect(await until(() => hook.events.some((e) => e.type === "user.upsert"))).toBe(true);
  });

  it("only admins reach /admin/*, and only they may create organizations", async () => {
    expect((await call("/admin/status", { headers: { cookie: ada } })).status).toBe(403);
    const refused = await call("/api/auth/organization/create", { method: "POST", headers: { cookie: ada, "content-type": "application/json" }, body: JSON.stringify({ name: "Administrators", slug: "administrators" }) });
    expect(refused.status).toBe(403);

    admin = await verifiedUser("admin@example.test", "Grace Hopper");
    const status = await call("/admin/status", { headers: { cookie: admin } });
    expect(status.status).toBe(200);
    expect(await status.json()).toMatchObject({ failed: 0 });
  });

  it("an organization is a group at the app, with its provisioned members", async () => {
    const org = await call("/api/auth/organization/create", { method: "POST", headers: { cookie: admin, "content-type": "application/json" }, body: JSON.stringify({ name: "Acme", slug: "acme" }) });
    expect(org.status, await org.clone().text()).toBe(200);
    expect(await until(() => [...app.groups.values()].some((g) => g.displayName === "Acme" && g.members.length === 1))).toBe(true);
    expect(await until(() => hook.events.some((e) => e.type === "group.upsert"))).toBe(true);
  });

  it("a failed delivery is retried by the Cron Trigger", async () => {
    app.fail({ status: 503 });
    const renamed = await call("/api/auth/update-user", { method: "POST", headers: { cookie: ada, "content-type": "application/json" }, body: JSON.stringify({ name: "Ada King" }) });
    expect(renamed.status).toBe(200);
    const user = () => [...app.users.values()].find((u) => u.userName === "ada@example.test");
    await new Promise((r) => setTimeout(r, 300));
    expect(user()?.displayName).toBe("Ada Lovelace");

    // The retry waits its backoff (30 seconds first); make it due now, in the stored date format.
    const db = await mf.getD1Database("DB");
    const job = await db.prepare('SELECT "nextAttemptAt" FROM "scimProvisioningJob" WHERE "failed" = 0').first<{ nextAttemptAt: string | number }>();
    expect(job).toBeTruthy();
    const past = new Date(Date.now() - 1000);
    await db.prepare('UPDATE "scimProvisioningJob" SET "nextAttemptAt" = ?').bind(typeof job!.nextAttemptAt === "number" ? past.getTime() : past.toISOString()).run();
    const worker = (await mf.getWorker()) as unknown as { scheduled(o: { cron: string }): Promise<unknown> };
    await worker.scheduled({ cron: "*/5 * * * *" });
    expect(await until(() => user()?.displayName === "Ada King")).toBe(true);
  });

  it("a deleted account is deactivated at the app", async () => {
    const del = await call("/api/auth/delete-user", { method: "POST", headers: { cookie: ada, "content-type": "application/json" }, body: JSON.stringify({ password: "correct-horse-battery" }) });
    expect(del.status, await del.clone().text()).toBe(200);
    expect(await until(() => [...app.users.values()].find((u) => u.userName === "ada@example.test")?.active === false)).toBe(true);
  });

  it("an admin can reconcile and run on demand", async () => {
    const reconciled = await call("/admin/reconcile", { method: "POST", headers: { cookie: admin } });
    expect(reconciled.status).toBe(200);
    expect(((await reconciled.json()) as { queued: number }).queued).toBeGreaterThan(0);
    const ran = await call("/admin/run", { method: "POST", headers: { cookie: admin } });
    expect(ran.status).toBe(200);
    expect(await (await call("/admin/status", { headers: { cookie: admin } })).json()).toMatchObject({ queued: 0, failed: 0 });
  });
});
