-- Better Auth, its admin and organization plugins, and better-auth-scim-provisioning.
-- Generated by Better Auth's migrator; test/example/workers.test.ts checks it's current.
create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null, "role" text, "banned" integer, "banReason" text, "banExpires" date);

create table "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "impersonatedBy" text, "activeOrganizationId" text);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

create table "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" date not null, "metadata" text);

create table "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" date not null);

create table "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" date not null, "createdAt" date not null, "inviterId" text not null references "user" ("id") on delete cascade);

create table "scimProvisioningJob" ("id" text not null primary key, "key" text not null unique, "targetId" text not null, "userId" text not null, "version" integer not null, "attempts" integer not null, "nextAttemptAt" date not null, "lockedUntil" date not null, "failed" integer not null, "lastError" text, "lastStatus" integer, "kind" text, "createdAt" date not null, "updatedAt" date not null);

create table "scimProvisioningLink" ("id" text not null primary key, "key" text not null unique, "targetId" text not null, "userId" text not null, "remoteId" text not null, "userName" text not null, "externalId" text, "active" integer not null, "syncedAt" date not null);

create table "scimProvisioningGroupLink" ("id" text not null primary key, "key" text not null unique, "targetId" text not null, "organizationId" text not null, "remoteId" text not null, "displayName" text not null, "syncedAt" date not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create index "member_organizationId_idx" on "member" ("organizationId");

create index "member_userId_idx" on "member" ("userId");

create index "invitation_organizationId_idx" on "invitation" ("organizationId");

create index "invitation_email_idx" on "invitation" ("email");

create index "scimProvisioningJob_userId_idx" on "scimProvisioningJob" ("userId");

create index "scimProvisioningJob_nextAttemptAt_idx" on "scimProvisioningJob" ("nextAttemptAt");

create index "scimProvisioningLink_targetId_idx" on "scimProvisioningLink" ("targetId");

create index "scimProvisioningLink_userId_idx" on "scimProvisioningLink" ("userId");

create index "scimProvisioningLink_remoteId_idx" on "scimProvisioningLink" ("remoteId");

create index "scimProvisioningGroupLink_targetId_idx" on "scimProvisioningGroupLink" ("targetId");

create index "scimProvisioningGroupLink_remoteId_idx" on "scimProvisioningGroupLink" ("remoteId");
